import Head from 'next/head'
import { Inter } from 'next/font/google'
import { menu} from '../components/menu'
import Link from 'next/link'
import Assist from './assist'
import styles from '@/styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Combined AI voice app</title>
        <meta name="description" content="Generated by next app for Hybrid environments" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Assist/>
    </>
  )
}
